# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: marcus kuehne | ux designer
email: marcus.kuehne(at)t-online.de
description: Interaction Designer, User Experience Specialist and user experience designer 
  who is interested in code, design,typography and all the magical web development stuff.
baseurl: ""
url: "http://marcuskuehne.de" # the base hostname & protocol for your site

sass:
  sass_dir: _sass
include: ['_pages']

# Build settings
markdown: kramdown
